[[https://coveralls.io/github/ychubachi/org-sync-qiita][https://coveralls.io/repos/github/ychubachi/org-sync-qiita/badge.svg?branch=main]]

* org-sync-qiita
Emacs Orgで作成した記事を一瞬でQiitaに投稿するコマンドです。

* 利用の流れ
** アクセストークンを取得する
こちらのページからアクセストークンを取得します。
- [[https://qiita.com/settings/tokens/new][アクセストークンの発行]]

手順は次のとおりです。
- 説明に「org-sync-qiita」と書く
- スコープは「read_qiita」と「write_qiita」
- 「発行する」ボタンを押す
- アクセストークンが表示されるので、 +復活の呪文のごとく紙にメモする+ クリップボードにコピーしておきましょう。

** 記事を書く
Emacsを使い、次のようにOrgで記事を書きます。

#+begin_src org
  ,* 記事のタイトル
  記事の本文です。
  ,** サブタイトル1
  記事の本文です。
  ,** サブタイトル2
  記事の本文です。
#+end_src

** 記事を限定公開する
カーソルを「記事のタイトル」のヘッドライン（最初の行）に合わせて ~M-x org-sync-qiita-at-point~ と打ちます。

ミニバッファにアクセストークンを入力します。

#+begin_example
Qiita access-token: xxxxxxxxxxx （←Qiitaのアクセストークン）
#+end_example

GPGで暗号化して保存するため、パスワードを聞かれますので任意のものを入力してください。

その後、次の通りヘッドラインにプロパティが追加されます。

#+begin_src org
  ,* 記事のタイトル
  :PROPERTIES:
  :QIITA-ID: 684fxxxxxd6a9xxxxx3d
  :QIITA-PRIVATE: true
  :QIITA-TAGS: org
  :QIITA-URL: https://qiita.com/ychubachi/private/684fxxxxxd6a9xxxxx3d
  :END:

  記事の本文です。
#+end_src

「QIITA-URL」プロパティのリンクを開くと「限定公開」で記事が投稿できていることが分かります。

** 記事を更新する

その後、本文を執筆し、再度 ~M-x org-sync-qiita-at-point~ を実行すると記事が更新されます。2回目以降は、カーソルが本文中にあっても正しく動作します。

タグはディフォルトで「org」が付きます。変更するには ~QIITA-TAGS~ にカンマ区切りで入力してください。

** 記事を公開する

記事が完成したら、 ~QIITA-PRIVATE~ タグを ~false~ に書き換えてください。 ~M-x org-sync-qiita-at-point~ を実行すると記事が公開されます。

* 導入方法

init.elに次の設定を行ってください。MELPA等に登録していないので、GitHubから
ダウンロードしてください。

** [[https://github.com/raxod502/straight.el][straight.el]] をお使いの場合

#+begin_src emacs-lisp
  (straight-use-package '(org-sync-qiita :type git :host github
                                         :repo "ychubachi/org-sync-qiita"))
#+end_src

#+RESULTS:
: t

** [[https://github.com/conao3/leaf.el][leaf.el]] と組み合わせるなら

#+begin_src emacs-lisp
  (leaf org-sync-qiita
    :straight (org-sync-qiita :type git :host github
                              :repo "ychubachi/org-sync-qiita"))
#+end_src

#+RESULTS:
: org-sync-qiita

* カスタマイズ

暗号化したアクセストークンは次のファイルに保存されます。

#+begin_example
~/.emacs.d/qiita.plstore
#+end_example

変更したい場合、変数 ~org-sync-qiita-access-token-file~ を変えてください。

* 制限事項
- 一度公開したものを限定公開には戻せません。
  - [[https://help.qiita.com/ja/articles/qiita-private-article][※記事を限定共有から公開することは出来ますが、一旦投稿した記事を限定共有にすることは出来ません。]]
- twitterへの自動投稿には対応していません。
- 画像には対応していません。
- その他不具合がありましたらissueに登録して頂けると嬉しいです（日本語歓迎）。
